Gruntfile.js

Using `strictMath` to prevent Less from trying to calculate stuff it's shouldn't calculate.
Example:
The following Less:
```less
.small {
width: calc(~"100% / 12 * 6 - 40px");
}
```
will output the following CSS:
```css
.small {
width: -webkit-calc(100% / 12 * 7 - 40px);
width: calc(100% / 12 * 7 - 40px);
}
```
which is as expected. The calculation can be performed at runtime.
But the minified version will be:
```css
.small{width:-webkit-calc(18.33333333%);width:calc(18.33333333%)}
```
and that's something else (the absolute part, 40px, shouldn't be converted to something relative).
By using `strictMath: true` both the CSS and the minified CSS will contain the entire calculation.

Using strictMath

---

README.md

The link to Mark Otto's GitHub account is incorrect. This fixes it.

Fix link to Mark Otto's GitHub Account

---

api/2.json

The API for version 2 didn't contain a css cdn pointer.

Add css CDN to API Version 2

---

paper/_bootswatch.scss
paper/bootswatch.less

When using the various input feedback styles, `.has-warning`, `.has-error` and `.has-success`, Bootstrap applies a colored border and background to `.input-group-addon`s in `_forms.scss` which uses the brand colors styles directly and not dedicated variables.
This patch adds styles to `paper/_bootswatch.scss` and `paper/_bootswatch.less` to reset this using the input-addon variables used for the default addons without feedback. The result is that if there is feedback the input is underlined according to material rules and the addon is unaffected. I couldn't spot a Material Design rule for addons, but I think this works quite well. An alternative might be to have the font color of the addon change according to the feedback.
Tested for SASS; not tested for LESS, although it l think the …

Paper: Reset input-addon feedback styles.

---

united/_variables.scss
united/variables.less

Updating Ubuntu orange color per https://design.canonical.com/2016/04/ubuntu-orange-update/

united: update Ubuntu orange

---

help/index.html

Hi, thanks for your work in this project!
While following the Help instructions for customizing a theme I got confused when my sass variables and styles weren't being included on the bundled styles. 
Then I noticed the dual less/sass files (I directly search for the sass file) and had to dive in the Gruntfile to figure out there was another task to process the scss files.
I thought to contribute a bit by updating the docs. Please let me know if you want any changes on they wording/order/whatever.

Updating Help doc to include sass workflow

---

4-alpha/index.html

The link on the /v4-alpha/index.html page was leading to a 404.

Fixed link from /3/ to /

---

bootswatch.gemspec

I'd like to propose adding a .gemspec file to the repo.  Doing so would give Rubyists an easy way to access the most up-to-date version of any theme by adding the following to their Gemfile:
```ruby
gem "bootswatch", github: "thomaspark/bootswatch"
```
Furthermore, Rails users can then add the following line to an initializer:
```ruby
Rails.application.config.assets.paths += Gem.loaded_specs["bootswatch"].load_paths
```
And thus be able to import themes via any SCSS asset like so:
```scss
@import "materia/variables";
@import "materia/bootswatch";
```
The `bootswatch.gemspec` file I've included in this PR dynamically pulls all its metadata from `package.json`.  Thus it should not need to be updated, and should not pose an extra maintainence burden.  Any time you update `package.json`, the …

Add gemspec

---

README.md

This is a follow-up to #822.
I fleshed out the "Usage" section of the README a little bit.  I also changed the markdown for all of the headers for consistency, since there is no way to produce `<h3>` headers via underscoring.  For the "Usage" section, I wrapped the text at 80 characters, but I left the rest of the file unwrapped because I didn't want to complicate the diff.
If you have any feedback or would like any changes, just let me know!

Update README with more usage information

---

bootswatch.gemspec

Follow-up to #822 
The Ruby package manager, Bundler, chokes on the "+" in a version number like "4.1.0+1".  This fix translates "+" to "." in the version number read from package.json.
Sorry for not anticipating this problem! :sweat:

Coerce version number to Bundler-accepted format

---

dist/cyborg/_bootswatch.scss

This adds `color: white` to `.input-group-text` and `.custom-file-label::after` which are needed to make pieces of input addons and file uploads show properly.
Before: 
After:

Cyborg theme: Add two additional form color settings

---

docs/cerulean/index.html
docs/cosmo/index.html
docs/cyborg/index.html
docs/darkly/index.html
docs/default/index.html
docs/flatly/index.html
docs/index.html
docs/journal/index.html
docs/litera/index.html
docs/lumen/index.html
docs/lux/index.html
docs/materia/index.html
docs/minty/index.html
docs/pulse/index.html
docs/sandstone/index.html
docs/simplex/index.html
docs/sketchy/index.html
docs/slate/index.html
docs/solar/index.html
docs/spacelab/index.html
docs/superhero/index.html
docs/united/index.html
docs/yeti/index.html

This PR implements the direct download of the `bootstrap.min.css` from the homescreen. The user doesn't expect to open a new window when clicking _Download_.
If desired, I can also add the download attribute to the dropdown menu, as I think most users want to download the file and not view it as a raw text in the browser.....

Direct download

---

cosmo/bootswatch.less
cyborg/bootswatch.less
darkly/bootswatch.less
flatly/bootswatch.less
journal/bootswatch.less
lumen/bootswatch.less
paper/bootswatch.less
readable/bootswatch.less
sandstone/bootswatch.less
simplex/bootswatch.less
spacelab/bootswatch.less
superhero/bootswatch.less
united/bootswatch.less
yeti/bootswatch.less

Bootswatch 3 won't compile under less 3 as reported in 
* https://github.com/thomaspark/bootswatch/issues/841
* https://github.com/thomaspark/bootswatch/issues/842
A fixed was made on 15/6/18 by: https://github.com/thomaspark/bootswatch/commit/5467d71dc140144eb452acfa761b879fe869da29, but the fix was never actually applied the v3 branch.
So Bootswatch 3.4.1, released after the fix on 13/2/19, is still incompatible with less 3.
This fix adds the original fix to the v3 branch.
Since there probably won't be a bootstrap 3.4.2, at least not in the near future, maybe you could release a 3.4.1+1 wit this fix?

fix remote font imports for less 3 again

---

dist/lux/_bootswatch.scss
docs/4/lux/_bootswatch.scss

I noticed that changing the primary theme color by overriding the primary color variable doesn't affects some of the elements backgound color. This happens because the .bg-primary is using gray-900 variable rather than primary variable. Although the primary variable is pointing to the same grey-900 variable, but changing the value of the primary variable doesn't change the .bg-primary. This change (commit) fixed that, and makes changing the theme primary color (including bg-primary) easy by only overriding the value of a single variable (primary).

Change the Theme Primary Background to Primary Color

---

dist/cosmo/_variables.scss

Previously Segoe UI was declared first.
@thomaspark let me know if you intentionally had left out the other fonts. But Open Sans Pro should come first otherwise is not used on Windows since Segoe UI was first.

cosmo: fix fonts.

---

dist/materia/_variables.scss

Bootstrap already escapes these characters, and charset is unneeded.
Generated CSS diff:
```diff
dist/materia/bootstrap.css | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
diff --git a/dist/materia/bootstrap.css b/dist/materia/bootstrap.css
index dbb97c83..55dd0a00 100644
--- a/dist/materia/bootstrap.css
+++ b/dist/materia/bootstrap.css
@@ -3880,7 +3880,7 @@ input[type="button"].btn-block {
}
.custom-radio .custom-control-input:checked ~ .custom-control-label::after {
-  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3E%3Ccircle r='4' fill='%232196F3'/%3E%3C/svg%3E");
+  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3e%3ccircle r='4' …
```

materia: use the decoded SVG and remove charset.

---

docs/3/assets/js/bsa.js

BTW @thomaspark it seems there is a reference in swatchmaker's test, but it was referencing the root bsa.js

Delete the unused bsa.js

---

dist/sketchy/_bootswatch.scss

This extra comma causes issues with some compilers

Remove extra comma

---

dist/lux/_variables.scss

[Can cause issues](https://github.com/rstudio/bslib/issues/215) for other Sass code that listens to `$input-btn-border-width`

Don't set (unused) $input-btn-border-width in lux theme

---

.browserslistrc

This should get rid of plenty of vendor prefixes which are useless since those browsers aren't supported by Bootstrap itself.

Update .browserslistrc to Bootstrap's v5 one

---

Gruntfile.js
dist/quartz/_variables.scss
package-lock.json
package.json

This is what Bootstrap v5 is using since node-sass is deprecated.
Requires #1147 
Note that this changes the dist files a lot. I used the `* .5` workaround to fix the Sass division warning but keep compatibility with node-sass.

Switch to the sass package.

---

dist/materia/_bootswatch.scss
dist/morph/_bootswatch.scss
dist/quartz/_bootswatch.scss

* IE is not supported
* `::file-selector-button` is handled by autoprefixer
Should be merged after #1147.

Clean up prefixes

---

docs/_assets/scss/custom.scss

* `box-shadow` isn't set anymore
* `.navbar-nav > .open > a` does not exist; not sure if it's supposed to be `.show` but no box-shadow is set anyway
* moved the background fallback color to the background shorthand; it's probably moot though, so this can just be `background-image: $gradient;` AFAICT

docs: clean up Sass code

---

.github/workflows/ci.yml
Gruntfile.js
package-lock.json
package.json

Better not squash these @thomaspark :) You should be able to merge and bump version + run your scripts and then release it.
Make sure you don't use the `latest` npm tag though since currently v5.1.3 is the latest one. We went with `latest-4` upstream.

v4-dev patches

---

dist/cyborg/_variables.scss
dist/darkly/_variables.scss
dist/flatly/_variables.scss
dist/litera/_variables.scss
dist/lumen/_variables.scss
dist/minty/_variables.scss
dist/quartz/_variables.scss
dist/slate/_variables.scss
dist/solar/_variables.scss
dist/superhero/_variables.scss
dist/vapor/_variables.scss
dist/yeti/_variables.scss
docs/5/cyborg/_variables.scss
docs/5/darkly/_variables.scss
docs/5/flatly/_variables.scss
docs/5/litera/_variables.scss
docs/5/lumen/_variables.scss
docs/5/minty/_variables.scss
docs/5/quartz/_variables.scss
docs/5/slate/_variables.scss
docs/5/solar/_variables.scss
docs/5/superhero/_variables.scss
docs/5/vapor/_variables.scss
docs/5/yeti/_variables.scss

Fix for Sass depreciation (Breaking Change: Strict Function Units): https://sass-lang.com/d/function-units.
This resolves the below build error:
"Deprecation $weight: Passing a number without unit % (0) is deprecated.
To preserve current behavior: $weight * 1%
More info: https://sass-lang.com/d/function-units"

Fix Sass warning: Passing a number without unit % (0) is deprecated

---

docs/cerulean/index.html
docs/cosmo/index.html
docs/cyborg/index.html
docs/darkly/index.html
docs/default/index.html
docs/flatly/index.html
docs/journal/index.html
docs/litera/index.html
docs/lumen/index.html
docs/lux/index.html
docs/materia/index.html
docs/minty/index.html
docs/morph/index.html
docs/pulse/index.html
docs/quartz/index.html
docs/sandstone/index.html
docs/simplex/index.html
docs/sketchy/index.html
docs/slate/index.html
docs/solar/index.html
docs/spacelab/index.html
docs/superhero/index.html
docs/united/index.html
docs/vapor/index.html
docs/yeti/index.html
docs/zephyr/index.html

Summary: The ```text-info-emphasis``` example was missing the ```-emphasis``` suffix from its class definition. Here is a pull request to fix all examples.
Old: ```<p class="text-info">.text-info-emphasis</p>```
New: ```<p class="text-info-emphasis">.text-info-emphasis</p>```
Files Affected:
modified:   docs/cerulean/index.html
modified:   docs/cosmo/index.html
modified:   docs/cyborg/index.html
modified:   docs/darkly/index.html
modified:   docs/default/index.html
modified:   docs/flatly/index.html
modified:   docs/journal/index.html
modified:   docs/litera/index.html
modified:   docs/lumen/index.html
modified:   docs/lux/index.html
modified:   docs/materia/index.html
modified:   docs/minty/index.html
modified:   docs/morph/index.html
modified:   docs/pulse/index.html
modified: …

Fixing incorrect text-info-emphasis example for theme demos
