thomaspark/bootswatch

- Gruntfile.js
- cerulean/_variables.scss
- cosmo/_variables.scss
- custom/_variables.scss
- cyborg/_variables.scss
- darkly/_variables.scss
- flatly/_variables.scss
- journal/_variables.scss
- lumen/_variables.scss
- paper/_variables.scss
- readable/_variables.scss
- sandstone/_variables.scss
- simplex/_variables.scss
- slate/_variables.scss
- spacelab/_variables.scss
- superhero/_variables.scss
- united/_variables.scss
- yeti/_variables.scss
Update Grunt so the !default flag is assigned to all _variables.scss files.
Fixes #450
> Set Sass !default flag

- README.md
This PR adds [bootswatch-rails](https://github.com/maxim/bootswatch-rails) link for the Rails users using SASS.
> Link to `bootswatch-rails`.

- README.md
- help/index.html
> Update API info

- README.md
> Remove the less link

- cerulean/_variables.scss
- cosmo/_variables.scss
- cyborg/_variables.scss
- darkly/_variables.scss
- flatly/_variables.scss
- journal/_variables.scss
- litera/_variables.scss
- lumen/_variables.scss
- lux/_variables.scss
- materia/_variables.scss
- minty/_variables.scss
- pulse/_variables.scss
- sandstone/_variables.scss
- simplex/_variables.scss
- sketchy/_variables.scss
- slate/_variables.scss
- solar/_variables.scss
- spacelab/_variables.scss
- superhero/_variables.scss
- united/_variables.scss
- yeti/_variables.scss
Added '! default' to all variables that did not have it, to allow for theme customization (overrides).
Used following regex:
find: ^(\$((?!default).)*);$
replace with: $1 !default;
Proposed fix for #667
> Proposed fix for #667

- dist/cerulean/_bootswatch.scss
- dist/cyborg/_variables.scss
- dist/darkly/_bootswatch.scss
- dist/darkly/_variables.scss
- dist/flatly/_bootswatch.scss
- dist/lux/_bootswatch.scss
- dist/materia/_bootswatch.scss
- dist/sandstone/_variables.scss
- dist/united/_bootswatch.scss
- docs/4/cerulean/_bootswatch.scss
- docs/4/cyborg/_variables.scss
- docs/4/darkly/_bootswatch.scss
- docs/4/darkly/_variables.scss
- docs/4/flatly/_bootswatch.scss
- docs/4/lux/_bootswatch.scss
- docs/4/materia/_bootswatch.scss
- docs/4/sandstone/_variables.scss
- docs/4/united/_bootswatch.scss
* consistency: convert tabs to spaces 💅 
* remove trailing whitespace
[because the `grunt` task touched way to many files, I've just commited the "`source-files`"]
> convert tabs to spaces

- dist/cyborg/_bootswatch.scss
- dist/cyborg/bootstrap.css
- dist/darkly/_bootswatch.scss
- dist/darkly/bootstrap.css
- dist/flatly/_bootswatch.scss
- dist/flatly/bootstrap.css
- dist/litera/_bootswatch.scss
- dist/materia/_bootswatch.scss
- dist/materia/bootstrap.css
- dist/slate/_bootswatch.scss
- dist/solar/_bootswatch.scss
- dist/solar/bootstrap.css
- dist/superhero/_bootswatch.scss
- dist/superhero/bootstrap.css
- docs/4/cyborg/_bootswatch.scss
- docs/4/cyborg/bootstrap.css
- docs/4/darkly/_bootswatch.scss
- docs/4/darkly/bootstrap.css
- docs/4/flatly/_bootswatch.scss
- docs/4/flatly/bootstrap.css
- docs/4/litera/_bootswatch.scss
- docs/4/materia/_bootswatch.scss
- docs/4/materia/bootstrap.css
- docs/4/slate/_bootswatch.scss
- docs/4/solar/_bootswatch.scss
- docs/4/solar/bootstrap.css
- docs/4/superhero/_bootswatch.scss
- docs/4/superhero/bootstrap.css
* use theme-color modifiers for `.alert-*`
📖 http://getbootstrap.com/docs/4.0/getting-started/theming/#modifiers
[because the `grunt` task touched way to many files, I've just commited the "`source-files`"]
> use theme-color modifiers for .alert-*

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
* update list-group markup
* see: https://getbootstrap.com/docs/4.0/components/list-group/
> update list-group markup

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
* update `.blockquote` markup
* add alignment variants `.text-center` / `.text-right`
* https://getbootstrap.com/docs/4.0/content/typography/#blockquotes
> update blockquotes markup

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
* update `.jumbotron` markup
* https://getbootstrap.com/docs/4.0/components/jumbotron/
> update jumbotron markup

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
* update `.card` markup
* add `.list-group`
* add simple `.card-body` example
* https://getbootstrap.com/docs/4.0/components/card/#card-styles
* https://getbootstrap.com/docs/4.0/components/card/#background-and-color
* https://getbootstrap.com/docs/4.0/components/card/#border
---
💡 Some themes have minor color contrast issues with `.header` and headlines.
> update card markup

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
* update form markup
* add `.form-control-plaintext` example
* use `.valid-feedback`
* use `.invalid-feedback`
* add disabled checkbox
* fix indentation
* add custom forms section
> update form markup

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
* update alert example
* https://getbootstrap.com/docs/4.0/components/alerts/#additional-content
> update alert example

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
* use `.flex-column` for vertical navigation
* show first tab content
> update nav example

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
* update table markup
* https://getbootstrap.com/docs/4.0/content/tables/#contextual-classes
> update table markup

- dist/sketchy/_variables.scss
> Fix Sketchy theme's $dark variable

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
* checkbox or radio style button toggling markup
via: https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons
> update checkbox or radio style button toggling markup

- README.md
- docs/help/index.html
Hi there 👋 
Thanks @thomaspark for this great resource!
I wanted to contribute back a tiny bit of documentation to help users of JS+CSS bundlers.
Mainly geared toward `create-react-app`.
It's `React` flavored due to it's current (2019) prominence, let me know if you think the "angle" needs to change.
> Update npm instructions

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
Fixes/Closes #971 by adding a dropdown example to all navbar examples.
> Added a dropdown example to all navbar examples.

- dist/lux/_variables.scss
- dist/materia/_variables.scss
- dist/sketchy/_variables.scss
- dist/solar/_variables.scss
- dist/superhero/_variables.scss
- dist/yeti/_variables.scss
* remove units from zero
* use double quotes consistently
I will make another PR in the next days to add Stylelint.
> Minor Sass cleanup

- package-lock.json
- package.json
@thomaspark might be a good chance to update your Node.js version to the latest 12.x LTS alongside with the npm that ships with that version; the package-lock.json file was severely outdated
> Remove the unused grunt-contrib-uglify

- package-lock.json
- package.json
If it conflicts later, let me know and I'll rebase it @thomaspark
> Remove the unused websocket-driver dependency

- dist/materia/_variables.scss
- docs/4/materia/_variables.scss
Just that, I am trying to customize that theme and it would be great if gradients can be disabled via variable override.
> Use !default on materia $enable-gradients

- dist/materia/_bootswatch.scss
If there any conflicts later, ping me to rebase :)
> Slightly improve the base64 images' compression

- Gruntfile.js
Trying to improve the current situation :)
~~Only thing left is to copy only a specific theme's files and not all.~~ **EDIT**: done!
> Tweak Gruntfile.js

- dist/cyborg/_bootswatch.scss
- dist/darkly/_bootswatch.scss
- dist/flatly/_bootswatch.scss
- dist/journal/_bootswatch.scss
- dist/litera/_bootswatch.scss
- dist/lumen/_bootswatch.scss
- dist/materia/_bootswatch.scss
- dist/minty/_bootswatch.scss
- dist/pulse/_bootswatch.scss
- dist/sandstone/_bootswatch.scss
- dist/simplex/_bootswatch.scss
- dist/sketchy/_bootswatch.scss
- dist/slate/_bootswatch.scss
- dist/solar/_bootswatch.scss
- dist/superhero/_bootswatch.scss
- dist/yeti/_bootswatch.scss
I need to go through the other variables and reuse them when possible
> Use the color variables when possible

- build/html/thumbnail.html
Not sure if the file is even used anymore, but I thought I'd format it.
Non-whitespace diff: <https://github.com/thomaspark/bootswatch/pull/1006/files?w=1>
> Format thumbnail.html

- Gruntfile.js
> Gruntfile.js: further cleanup

- docs/_assets/js/custom.js
Non-whitespace diff: <https://github.com/thomaspark/bootswatch/pull/1016/files?w=1>
> Lint custom.js

- dist/cyborg/_variables.scss
- dist/darkly/_variables.scss
- dist/flatly/_variables.scss
- dist/materia/_variables.scss
- dist/minty/_variables.scss
- dist/sandstone/_variables.scss
- dist/superhero/_variables.scss
- dist/united/_variables.scss
BTW @thomaspark shouldn't cyborg's font family include the defaults like the other themes do?
> Update font stack

- dist/flatly/_bootswatch.scss
- dist/litera/_bootswatch.scss
- dist/lumen/_bootswatch.scss
- dist/materia/_bootswatch.scss
- dist/minty/_bootswatch.scss
- dist/sandstone/_bootswatch.scss
- dist/slate/_bootswatch.scss
- dist/solar/_bootswatch.scss
- dist/yeti/_bootswatch.scss
- package-lock.json
- package.json
Also, fix unnecessary nesting selectors errors, which are now flagged
> Update stylelint-config-twbs-bootstrap to v2.1.0.

- package.json
Remove the build script; CI runs this separately
> Update npm test script

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
Spaces need to be escaped after all.
Regression of #1025
> Properly encode the data SVGs

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/help/index.html
- docs/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
This was semi-automated, but I think we should be good to go.
> Format HTML

- docs/help/index.html
This actually resulted in broken navbar image after the recent changes
> help: remove unneeded styles

- docs/cerulean/index.html
- docs/cosmo/index.html
- docs/cyborg/index.html
- docs/darkly/index.html
- docs/default/index.html
- docs/flatly/index.html
- docs/journal/index.html
- docs/litera/index.html
- docs/lumen/index.html
- docs/lux/index.html
- docs/materia/index.html
- docs/minty/index.html
- docs/pulse/index.html
- docs/sandstone/index.html
- docs/simplex/index.html
- docs/sketchy/index.html
- docs/slate/index.html
- docs/solar/index.html
- docs/spacelab/index.html
- docs/superhero/index.html
- docs/united/index.html
- docs/yeti/index.html
* `disabled` is a boolean attribute so no need to specify `=""`
* use three periods for consistency - I don't have a preference, if you prefer the Unicode symbol I can switch to that instead
* break line
> Minor HTML consistency changes

- dist/lumen/_bootswatch.scss
- dist/materia/_bootswatch.scss
Needs testing to make sure it's fine.
> Be explicit with the transitioned properties

- docs/2/api/themes.json
- docs/api/2.json
Better check the non-whitespace diff: <https://github.com/thomaspark/bootswatch/pull/1053/files?w=1>
> API v2: format, fix links and bring the 2 files on par

- .github/workflows/ci.yml
> CI: switch to Node.js 16

- docs/_assets/img/splash.svg
@thomaspark might be worth inlining this SVG in the CSS so that it's not blocking. Right now the CSS has to be downloaded and parsed for the image to load.
> Optimize splash.svg

- docs/_assets/js/custom.js
This should be clearer than before. Note that it could probably be simplified more; I'm not sure if it makes sense to even check for `sourceModalElem` or `sourceModal` before calling `show()`
> docs: minor JS tweaks

- dist/flatly/_bootswatch.scss
- dist/lumen/_bootswatch.scss
- dist/materia/_bootswatch.scss
- dist/sandstone/_bootswatch.scss
- dist/yeti/_bootswatch.scss
* optimize them with the latest SVGO
* use Bootstrap's `escape-svg` function
* remove `width` and `height` attributes
* use the color variables when possible
TODO:
> Improve inline SVGs

- Gruntfile.js
Not sure if you agree with the license header change, this is more consistent with what we use, but it's subjective
> Gruntfile.js: minor tweaks

- docs/api/5.json
Ran `sed -i 's/5.1.1/5.1.3/g' docs/api/5.json`
> Update api to v5.1.3

- dist/sketchy/_bootswatch.scss
> Comma separate rgb() usage in sketchy

- .npmrc
> Create .npmrc for older npm compatibility
